### ISSUE TITLE
没有不和谐

### ISSUE THREAD

**Issue by MIt-gancm** [xTaiwanPingLord/Akebi-GC-Release#2]
在中国v*n是违法的 正常情况下大陆网络不能使用不和谐 但我十分想用Akebi-GC. 免费版 可以给个链接吗 如果可以的话 您可以在QQ上开一个群聊 这个软件≈不和谐 谢谢你了

**Comment by GUchengnan2007** [comment]
2143346306

**Comment by xTaiwanPingLord** [comment]
@MIt-gancm 
No free version. 請不要在中華人民共和國實際管轄區域內散播與米哈游有關的第三方軟體。
